[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "psx-sys"
version = "1.0.1"
description = "A lightweight Linux system utility CLI"
requires-python = ">=3.10"
dependencies = [
    "psutil"
]

[tool.setuptools.packages.find]
include = ["psx*"]
exclude = ["website*"]

[project.scripts]
psx = "psx.main:main"
